apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/sa.scc.mcs: s0:c29,c24
    openshift.io/sa.scc.uid-range: 1001/10000
    openshift.io/sa.scc.supplemental-groups: 1001/10000
  name: project10
  labels:
    argocd.argoproj.io/managed-by: amr
