apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm6
  namespace: test
spec:
  dataVolumeTemplates:
  - apiVersion: cdi.kubevirt.io/v1beta1
    kind: DataVolume
    metadata:
      creationTimestamp: null
      name: vm6
    spec:
      source:
        http:
          url: https://cloud.centos.org/centos/10-stream/x86_64/images/CentOS-Stream-GenericCloud-x86_64-10-latest.x86_64.qcow2
      storage:
        storageClassName: thin-csi
        accessModes:
        - ReadWriteOnce
        volumeMode: Filesystem
        resources:
          requests:
            storage: 20Gi
  runStrategy: Always
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: vm6
        vm.kubevirt.io/workload: server
      creationTimestamp: null
      labels:
        kubevirt.io/domain: vm6
        kubevirt.io/size: small
    spec:
      nodeSelector:
        run-vms: 'yes'
      domain:
        memory:
          guest: 1Gi
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
          - disk:
              bus: virtio
            name: rootdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - masquerade: {}
            name: default
          networkInterfaceMultiqueue: true
          rng: {}
        machine:
          type: pc-q35-rhel8.6.0
        resources: {}
      evictionStrategy: LiveMigrate
      networks:
      - name: default
        pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
      - dataVolume:
          name: vm6
        name: rootdisk
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            user: user
            password: redhat
            chpasswd: { expire: False }
        name: cloudinitdisk
