---
# Source: ipi1-cluster-provisioning-non-prod/charts/cluster-provisioning-base-chart-dev/templates/agentinstall.yaml
apiVersion: extensions.hive.openshift.io/v1beta1
kind: AgentClusterInstall
metadata:
  name: 'ipi1'
  namespace: 'ipi1'
spec:
  clusterDeploymentRef:
    name: 'ipi1'
  holdInstallation: true
  provisionRequirements:
    controlPlaneAgents: 3
  imageSetRef:
    name: 'img4.17.3-multi-appsub'
  networking:
    networkType: 'OVNKubernetes'
    clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
    serviceNetwork:
    - 172.30.0.0/16
  sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC/lvpqqcqez+JU8re2RsIfp0zA01GPCVBTvTApvNE31LQjcxinskCy9SV1RlNFD5m8Mk2PjfkyfEp8iRAgT+eD12toqnMAXY7lysijexhx5f/yRbEOJKZteATmabLB+4QDtk3PuAxtka74lCCP/12LadvGfk23VUDndrAzSZEwiHMkx3cPaLWJx11NlszaYJ1lIlCA+i4mNr/36pGe6wH2FHMyFr04CwGeq8siO/2lfq1FPYYTkdcr1GJRxvyyLmuO8vCPZG8Y9ldkEWVM82gMXQqXfKXMjh8xeF0qXc6bBYqDMoXRkHRtyRINaP2jvHg5Y1MVkJ6FpZabySQfmxcR root@allinone.homelab.local'
---
# Source: ipi1-cluster-provisioning-non-prod/charts/cluster-provisioning-base-chart-dev/templates/clusterconfig.yaml
apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  annotations:
    agentBareMetal-agentSelector/autoSelect: "true"
    agentBareMetal-cpuArchitecture: x86_64
  labels:
    "cluster.open-cluster-management.io/clusterset": 'default'
  name: 'ipi1'
  namespace: 'ipi1'
spec:
  baseDomain: lab.home
  clusterInstallRef:
    group: extensions.hive.openshift.io
    kind: AgentClusterInstall
    name: 'ipi1'
    version: v1beta1
  clusterName: 'ipi1'
  platform:
    agentBareMetal:
      agentSelector: {}
  pullSecretRef:
    name: pullsecret-cluster-ipi1
---
# Source: ipi1-cluster-provisioning-non-prod/charts/cluster-provisioning-base-chart-dev/templates/addonconfig.yaml
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: ipi1
  namespace: ipi1
spec:
  applicationManager:
    enabled: true
  certPolicyController:
    enabled: true
  clusterLabels:
    cloud: BareMetal
    vendor: OpenShift
  clusterName: ipi1
  clusterNamespace: ipi1
  iamPolicyController:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
---
# Source: ipi1-cluster-provisioning-non-prod/charts/cluster-provisioning-base-chart-dev/templates/managedcluster.yaml
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: ipi1
  namespace: ipi1
  labels:
    cloud: BareMetal
    cluster.open-cluster-management.io/clusterset: default
    name: ipi1
    vendor: OpenShift
spec:
  hubAcceptsClient: true
  leaseDurationSeconds: 60
