kind: Secret
apiVersion: v1
metadata:
  name: pullsecret-myhi
  namespace: myhi
data:
  '.dockerconfigjson': 'eyJhdXRocyI6eyJjbG91ZC5vcGVuc2hpZnQuY29tIjp7ImF1dGgiOiJiM0JsYm5Ob2FXWjBMWEpsYkdWaGMyVXRaR1YySzNKb2JuTjFjSEJ2Y25SaFpXeG5ZVzU2YnpGd2VIUm1PRzl6YUd0MVpYRjRNR1ozZUhKb1oyRjBiMmRrT0RvMVQwOUNPRlZTV2pjNVJscFJObEJJU0VkTE1sbE1PRU5VVFZCVFRFaFJWVnBDVjFwR1NFWkZSamRFVjFWWk1ETkRSa1JWVHpOS1FVVlZVRmhHVWxoTCIsImVtYWlsIjoiYWVsZ2Fuem9AcmVkaGF0LmNvbSJ9LCJxdWF5LmlvIjp7ImF1dGgiOiJiM0JsYm5Ob2FXWjBMWEpsYkdWaGMyVXRaR1YySzNKb2JuTjFjSEJ2Y25SaFpXeG5ZVzU2YnpGd2VIUm1PRzl6YUd0MVpYRjRNR1ozZUhKb1oyRjBiMmRrT0RvMVQwOUNPRlZTV2pjNVJscFJObEJJU0VkTE1sbE1PRU5VVFZCVFRFaFJWVnBDVjFwR1NFWkZSamRFVjFWWk1ETkRSa1JWVHpOS1FVVlZVRmhHVWxoTCIsImVtYWlsIjoiYWVsZ2Fuem9AcmVkaGF0LmNvbSJ9LCJyZWdpc3RyeS5jb25uZWN0LnJlZGhhdC5jb20iOnsiYXV0aCI6Ik5USTNNemN6TlRKOGRXaGpMVEZRZUZSbU9FOVRTRXRWWlZGNE1FWlhlSEpvWjBGMFQyZEVPRHBsZVVwb1lrZGphVTlwU2xOVmVsVjRUV2xLT1M1bGVVcDZaRmRKYVU5cFNtMU9SMDEzVG5wb2JVNUVhelJaVjFFd1QwUlNhazlVYkdoTlZGRTBUbGRKZUU1cVdteFplbEV5V2xOS09TNUJWSEJsV1RjMmVXY3pkbFZtV21oV2VFZFZTMlpJU3pCNVpFbElVVmxFUkhBemVFNVNTWEp1VlU5d09FVnNObWR5VDIxSWFYbGlWSFZVUTFsclduZGpRMjAwZGxreldIWTJZWE5zYmtwbmJURjJaVmxEU3pWd2JtWnRZblZpY0ZCbVRYbFdXa2RtZGxaTmRVUlZTamQ2TFdKcFZTMWlSWFpyVG5kWU1FVjVTakJpY2xabU5rZHZSVTFKZUdaR05tNTBMVTF5WjNkaFdsTjVjV1J6VDFGc1pIbzVaVGhpV0dvNFlXZzNaR3cwYlhaNllWVlFRV1JQZGtkRlQxUnZZalJ1WHpOVU1WWXRaa3BpYTBad1FsYzRTVTB0YUVSemVraDRRV3QwV1hoa1gwd3phQzFXZVZNNFZWOVBURTV3UldFemJFOUxNMjQyZFRSTGNFUnZhbGhXVm5seFJFaDVTVGh3YjFSSlZ6bEpXbWMyVVdKUlppMDFPVVZVVG0xSU1tNXFRME0yWnpOYU5XSlFUMHhKTmt0MU9IcGlVSGhuVlhadlpXZDVhRVJwUWpZdFRUWlRWMFpsVVdrNU4zTlRNRU5JVWxwbVYwTmZhR2QzUXpSb2NrdE1UemRXV1MxV00zRTVkR0YwZFdKNlUwdGlZMHh6ZEZoMk9HeE1TVVJXU1cxbVgyVnJaSFZvYmpoR05VdDBiazh5VWpreE9UWkZaMVp2YzFBeU1VRkVOMnhKV1RaNFpXSmZWR1JEUVhWNU4wRnlSVWRmU0VadVpWQmFZVEJ1UzBkUVVubFdOR054Y0dkUVpIaDRkRW8xWVhkV2JERnVaelUyWjNGWFpsWTFaM0U1YTBWa2FGVldhVEZ3Wm5kbFQyUnlTRVpmVTI5elZUUnBiR3hpTW5kWlNWTTVjRk5yVUVKQmJqVjBORFF3WlZGWlRFbzRTMmc0VW5WaVgzbEhSRWs0T0doT2RIZFRWM1JRZVhKMk5tZ3hlVlJxTkd0V1pEaFdaMEY0V1VWa1dHUnNUQzFHV1dadVJtcDFTVVIzV25WTlVGWndSMjVtUTFOd01XOW5MWEZ6UTNseWMzTXdkM2N4VjFNMVRGbHplVk5FV1ZZNFgwbDZWRGt3WnpWTmNHaGxlblpwVEhCUGVHOXJkRlZtVGtad1pubENaMnM0TFhFME4zVkhkWFZ1TUhweVFuaFBTMWR3UmsxVVdRPT0iLCJlbWFpbCI6ImFlbGdhbnpvQHJlZGhhdC5jb20ifSwicmVnaXN0cnkucmVkaGF0LmlvIjp7ImF1dGgiOiJOVEkzTXpjek5USjhkV2hqTFRGUWVGUm1PRTlUU0V0VlpWRjRNRVpYZUhKb1owRjBUMmRFT0RwbGVVcG9Za2RqYVU5cFNsTlZlbFY0VFdsS09TNWxlVXA2WkZkSmFVOXBTbTFPUjAxM1RucG9iVTVFYXpSWlYxRXdUMFJTYWs5VWJHaE5WRkUwVGxkSmVFNXFXbXhaZWxFeVdsTktPUzVCVkhCbFdUYzJlV2N6ZGxWbVdtaFdlRWRWUzJaSVN6QjVaRWxJVVZsRVJIQXplRTVTU1hKdVZVOXdPRVZzTm1keVQyMUlhWGxpVkhWVVExbHJXbmRqUTIwMGRsa3pXSFkyWVhOc2JrcG5iVEYyWlZsRFN6VndibVp0WW5WaWNGQm1UWGxXV2tkbWRsWk5kVVJWU2pkNkxXSnBWUzFpUlhaclRuZFlNRVY1U2pCaWNsWm1Oa2R2UlUxSmVHWkdObTUwTFUxeVozZGhXbE41Y1dSelQxRnNaSG81WlRoaVdHbzRZV2czWkd3MGJYWjZZVlZRUVdSUGRrZEZUMVJ2WWpSdVh6TlVNVll0WmtwaWEwWndRbGM0U1UwdGFFUnpla2g0UVd0MFdYaGtYMHd6YUMxV2VWTTRWVjlQVEU1d1JXRXpiRTlMTTI0MmRUUkxjRVJ2YWxoV1ZubHhSRWg1U1Rod2IxUkpWemxKV21jMlVXSlJaaTAxT1VWVVRtMUlNbTVxUTBNMlp6TmFOV0pRVDB4Sk5rdDFPSHBpVUhoblZYWnZaV2Q1YUVScFFqWXRUVFpUVjBabFVXazVOM05UTUVOSVVscG1WME5mYUdkM1F6Um9ja3RNVHpkV1dTMVdNM0U1ZEdGMGRXSjZVMHRpWTB4emRGaDJPR3hNU1VSV1NXMW1YMlZyWkhWb2JqaEdOVXQwYms4eVVqa3hPVFpGWjFadmMxQXlNVUZFTjJ4SldUWjRaV0pmVkdSRFFYVjVOMEZ5UlVkZlNFWnVaVkJhWVRCdVMwZFFVbmxXTkdOeGNHZFFaSGg0ZEVvMVlYZFdiREZ1WnpVMlozRlhabFkxWjNFNWEwVmthRlZXYVRGd1puZGxUMlJ5U0VaZlUyOXpWVFJwYkd4aU1uZFpTVk01Y0ZOclVFSkJialYwTkRRd1pWRlpURW80UzJnNFVuVmlYM2xIUkVrNE9HaE9kSGRUVjNSUWVYSjJObWd4ZVZScU5HdFdaRGhXWjBGNFdVVmtXR1JzVEMxR1dXWnVSbXAxU1VSM1duVk5VRlp3UjI1bVExTndNVzluTFhGelEzbHljM013ZDNjeFYxTTFURmx6ZVZORVdWWTRYMGw2VkRrd1p6Vk5jR2hsZW5acFRIQlBlRzlyZEZWbVRrWndabmxDWjJzNExYRTBOM1ZIZFhWdU1IcHlRbmhQUzFkd1JrMVVXUT09IiwiZW1haWwiOiJhZWxnYW56b0ByZWRoYXQuY29tIn19fQo='
type: 'kubernetes.io/dockerconfigjson'
---
apiVersion: agent-install.openshift.io/v1beta1
kind: InfraEnv
metadata:
  name: myhi
  namespace: myhi
  labels:
    agentclusterinstalls.extensions.hive.openshift.io/location: Dubai
    networkType: dhcp
spec:
  agentLabels:
    'agentclusterinstalls.extensions.hive.openshift.io/location': Dubai
  pullSecretRef:
    name: pullsecret-myhi
  sshAuthorizedKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCf/CNr8ZyKQsdbXeQ3jVBrKHHtYTUJ0BzRi+nWbrWqHwLW2duByT2X/3K2xQxSeO7k9fIKfk4f+0KTie856JnR1dRE3aFGqB/6FLm0GTGhMkm59j+cgyvMijclGLjYLCj9rJPDnN2RNWsmho5BjIFO2r171Lzwhm9KYxUwOQmhd7OAx6IMNnfUmhpokNTSvADeMBVIj9kT0mKAFWQtU7yQEdOx3pzO3POz5tlOq5AwGRpdhF/7KP11xHAqRIyzZsFyhMresLqar5Bwm4QqngANRGm3R8iea9eMFR9fJHnUeqLsZFLihWYnVJJ1jeHmLANCV1BMCkixEU2vgu6Bt0paWUBWFHk4ZR3reSJvWfgDhT+x+p1UW4hANaybGpmt6DHYGEnKHQZGjTaVNbfzauNWB5w+OlW9EFl2MKVwTGykNkWKatuarxrMRJ78HQ4wkwW2LkQdiWrFPrTTroCQgH13KDHT6UhmvvxgLIs4z/DcqbZ9hFaBT5T6Sxp8iuxaTd0= amr@lt.mylab.local
  nmStateConfigLabelSelector:	
      matchLabels:	
        infraenvs.agent-install.openshift.io: myhi
  cpuArchitecture: x86_64
status:
  agentLabelSelector:
    matchLabels:
      'agentclusterinstalls.extensions.hive.openshift.io/location': Dubai
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: capi-provider-role
  namespace: myhi
rules:
  - verbs:
      - '*'
    apiGroups:
      - agent-install.openshift.io
    resources:
      - agents
